apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 439853743831.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 439853743831.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 3e8ef083
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
